/**
 * Code-graph adapter tests.
 *
 * The properties that matter are the ones about being WRONG, not about being useful:
 *
 *   - a stale graph must announce itself, because a confident answer about moved code is
 *     the failure mode this module mostly exists to prevent;
 *   - an unrecognised relation must be reported, because it is silently excluded from
 *     dependency traversal and turns "40 dependents" into "2" with nothing looking wrong;
 *   - an absent graph must cost nothing anywhere.
 *
 * Fixtures are hand-built rather than generated by Graphify, so the tests do not require
 * it to be installed and cannot break when its output changes shape — the real-schema
 * cases are pinned separately from the real graphs when they exist.
 */

import { test, describe, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import * as G from '../scripts/graph.mjs';

let tmp;

/** Write a graph.json in the Graphify (networkx node-link) shape. */
const writeGraph = (dir, { builtAt = null, links = [], nodes = null } = {}) => {
  const out = path.join(dir, 'graphify-out');
  fs.mkdirSync(out, { recursive: true });
  const g = {
    directed: false,
    multigraph: false,
    graph: {},
    nodes: nodes || [
      { id: 'base', label: 'BaseDoc', norm_label: 'basedoc', file_type: 'code', source_file: 'base.py', source_location: 'L1', community: 1 },
      { id: 'child', label: 'ChildDoc', norm_label: 'childdoc', file_type: 'code', source_file: 'child.py', source_location: 'L4', community: 1 },
      { id: 'caller', label: 'run', norm_label: 'run', file_type: 'code', source_file: 'main.py', source_location: 'L9', community: 2 },
      { id: 'holder', label: 'base.py', norm_label: 'base.py', file_type: 'code', source_file: 'base.py', source_location: 'L1', community: 1 },
    ],
    links,
    hyperedges: [],
  };
  if (builtAt) g.built_at_commit = builtAt;
  fs.writeFileSync(path.join(out, 'graph.json'), JSON.stringify(g));
  return path.join(out, 'graph.json');
};

const EDGES = [
  { source: 'child', target: 'base', relation: 'inherits', confidence: 'EXTRACTED', confidence_score: 1, weight: 1, source_file: 'child.py' },
  { source: 'caller', target: 'base', relation: 'calls', confidence: 'EXTRACTED', confidence_score: 1, weight: 1, source_file: 'main.py' },
  { source: 'holder', target: 'base', relation: 'contains', confidence: 'EXTRACTED', confidence_score: 1, weight: 1, source_file: 'base.py' },
];

before(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'jarvis-graph-'));
});
after(() => fs.rmSync(tmp, { recursive: true, force: true }));

const fresh = () => {
  const d = fs.mkdtempSync(path.join(tmp, 'repo-'));
  return d;
};

describe('an absent graph costs nothing', () => {
  test('findGraph returns null rather than throwing', () => {
    assert.equal(G.findGraph(fresh()), null);
  });

  test('open() returns null, so every caller can treat it as optional', () => {
    assert.equal(G.open(fresh()), null);
  });
});

describe('finding a graph', () => {
  test('found in the directory itself', () => {
    const d = fresh();
    writeGraph(d, { links: EDGES });
    assert.ok(G.findGraph(d));
  });

  test('found by walking UP from a subdirectory', () => {
    // An agent is usually dispatched against a subdirectory while the graph is built at
    // the repo root. Searching only cwd reported "no graph" on a repo that has one.
    const d = fresh();
    writeGraph(d, { links: EDGES });
    const deep = path.join(d, 'a', 'b', 'c');
    fs.mkdirSync(deep, { recursive: true });
    assert.ok(G.findGraph(deep), 'did not search upward');
  });
});

describe('staleness is announced, not assumed', () => {
  const git = (d, args) => execFileSync('git', args, { cwd: d, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();

  const repoWithCommit = () => {
    const d = fresh();
    execFileSync('git', ['init', '-q'], { cwd: d, stdio: 'ignore' });
    execFileSync('git', ['config', 'user.email', 't@t'], { cwd: d, stdio: 'ignore' });
    execFileSync('git', ['config', 'user.name', 't'], { cwd: d, stdio: 'ignore' });
    fs.writeFileSync(path.join(d, 'a.txt'), 'one');
    execFileSync('git', ['add', '-A'], { cwd: d, stdio: 'ignore' });
    execFileSync('git', ['commit', '-qm', 'one'], { cwd: d, stdio: 'ignore' });
    return d;
  };

  test('a graph built at HEAD is fresh', () => {
    const d = repoWithCommit();
    const head = git(d, ['rev-parse', 'HEAD']);
    const f = writeGraph(d, { builtAt: head, links: EDGES });
    const g = G.load(f);
    assert.equal(g.freshness.state, 'fresh', g.freshness.detail);
    assert.match(G.freshnessNote(g), /current/);
  });

  test('a graph built at an older commit is STALE and says how far behind', () => {
    const d = repoWithCommit();
    const old = git(d, ['rev-parse', 'HEAD']);
    fs.writeFileSync(path.join(d, 'a.txt'), 'two');
    execFileSync('git', ['commit', '-aqm', 'two'], { cwd: d, stdio: 'ignore' });
    const g = G.load(writeGraph(d, { builtAt: old, links: EDGES }));
    assert.equal(g.freshness.state, 'stale');
    assert.equal(g.freshness.behind, '1');
    const note = G.freshnessNote(g);
    assert.match(note, /STALE GRAPH/);
    assert.match(note, /worse than none/, 'the warning did not say why staleness matters');
    assert.match(note, /graphify/, 'the warning did not say how to fix it');
  });

  test('a graph with no recorded commit is UNKNOWN, not fresh', () => {
    // "Cannot check" and "checked and fine" must never render the same.
    const g = G.load(writeGraph(repoWithCommit(), { links: EDGES }));
    assert.equal(g.freshness.state, 'unknown');
    assert.match(G.freshnessNote(g), /UNKNOWN/);
  });
});

describe('dependency traversal', () => {
  const g = () => G.load(writeGraph(fresh(), { links: EDGES }));

  test('reverse edges are the blast radius', () => {
    const gg = g();
    const dep = G.dependents(gg, 'base');
    const ids = dep.map((d) => d.id);
    assert.ok(ids.includes('child'), 'an inheritor was not counted as a dependent');
    assert.ok(ids.includes('caller'), 'a caller was not counted as a dependent');
  });

  test('`contains` is excluded by default — it is structure, not dependency', () => {
    // Over half the edges in a real graph are `contains`. Counting them floods every
    // blast radius with "this file holds that symbol", which is true and useless.
    const gg = g();
    assert.ok(!G.dependents(gg, 'base').some((d) => d.id === 'holder'));
    assert.ok(G.dependents(gg, 'base', { structural: true }).some((d) => d.id === 'holder'));
  });

  test('forward and reverse are different questions', () => {
    const gg = g();
    assert.equal(G.dependencies(gg, 'base').length, 0, 'base depends on nothing here');
    assert.ok(G.dependents(gg, 'base').length > 0);
  });

  test('INFERRED edges can be excluded', () => {
    const gg = G.load(
      writeGraph(fresh(), {
        links: [{ source: 'caller', target: 'base', relation: 'calls', confidence: 'INFERRED', weight: 1 }],
      })
    );
    assert.equal(G.dependents(gg, 'base', { includeInferred: false }).length, 0);
    assert.equal(G.dependents(gg, 'base', { includeInferred: true }).length, 1);
  });
});

describe('relation vocabularies', () => {
  test('BOTH observed vocabularies count as dependencies', () => {
    // Graphify emitted `inherits/implements/method/references` on a Python tree and
    // `extends/imports_from/dynamic_import/indirect_call` on a JavaScript one. Covering
    // only one silently halves every dependency count.
    for (const r of ['calls', 'imports', 'references', 'inherits', 'implements', 'method']) {
      assert.ok(G.DEPENDENCY_RELATIONS.has(r), `python vocab missing ${r}`);
    }
    for (const r of ['extends', 'imports_from', 'dynamic_import', 'indirect_call']) {
      assert.ok(G.DEPENDENCY_RELATIONS.has(r), `javascript vocab missing ${r}`);
    }
  });

  test('an unknown relation is REPORTED rather than silently dropped', () => {
    const gg = G.load(
      writeGraph(fresh(), {
        links: [{ source: 'child', target: 'base', relation: 'teleports_to', confidence: 'EXTRACTED', weight: 1 }],
      })
    );
    assert.deepEqual(G.unclassifiedRelations(gg), ['teleports_to']);
    const note = G.freshnessNote(gg);
    assert.match(note, /UNKNOWN RELATIONS/);
    assert.match(note, /FLOOR, not a total/, 'the caveat did not say the count is incomplete');
  });

  test('a fully-classified graph raises no relation warning', () => {
    const gg = G.load(writeGraph(fresh(), { links: EDGES }));
    assert.deepEqual(G.unclassifiedRelations(gg), []);
    assert.ok(!/UNKNOWN RELATIONS/.test(G.freshnessNote(gg)));
  });

  test('the three classifications do not overlap', () => {
    for (const r of G.DEPENDENCY_RELATIONS) {
      assert.ok(!G.STRUCTURAL_RELATIONS.has(r), `${r} is both a dependency and structural`);
      assert.ok(!G.SOFT_RELATIONS.has(r), `${r} is both a dependency and soft`);
    }
  });
});

describe('resolution prefers exact over fuzzy', () => {
  test('an exact label beats a substring match', () => {
    // Returning a fuzzy hit when an exact one exists is how a query about `Widget`
    // answers about `WidgetLedgerEntry` and nobody notices.
    const gg = G.load(
      writeGraph(fresh(), {
        links: EDGES,
        nodes: [
          { id: 'a', label: 'Doc', norm_label: 'doc', file_type: 'code', source_file: 'a.py' },
          { id: 'b', label: 'DocLedgerEntry', norm_label: 'docledgerentry', file_type: 'code', source_file: 'b.py' },
        ],
      })
    );
    assert.equal(G.resolve(gg, 'Doc')[0].id, 'a');
  });

  test('an id resolves directly', () => {
    const gg = G.load(writeGraph(fresh(), { links: EDGES }));
    assert.equal(G.resolve(gg, 'base')[0].id, 'base');
  });

  test('an empty query resolves to nothing rather than everything', () => {
    const gg = G.load(writeGraph(fresh(), { links: EDGES }));
    assert.deepEqual(G.resolve(gg, ''), []);
  });
});

describe('paths', () => {
  test('a path is found across an undirected edge', () => {
    const gg = G.load(writeGraph(fresh(), { links: EDGES }));
    const p = G.shortestPath(gg, 'child', 'caller');
    assert.ok(p, 'no path found through a shared neighbour');
    assert.equal(p[0].id, 'child');
    assert.equal(p[p.length - 1].id, 'caller');
  });

  test('disconnected nodes return null, not an empty path', () => {
    const gg = G.load(
      writeGraph(fresh(), {
        links: [],
        nodes: [
          { id: 'x', label: 'X', file_type: 'code', source_file: 'x.py' },
          { id: 'y', label: 'Y', file_type: 'code', source_file: 'y.py' },
        ],
      })
    );
    assert.equal(G.shortestPath(gg, 'x', 'y'), null);
  });
});

describe('malformed input degrades rather than throwing', () => {
  test('unparseable JSON is an error object, not an exception', () => {
    const d = fresh();
    const out = path.join(d, 'graphify-out');
    fs.mkdirSync(out, { recursive: true });
    fs.writeFileSync(path.join(out, 'graph.json'), '{ not json');
    const g = G.load(path.join(out, 'graph.json'));
    assert.equal(g.ok, false);
    assert.match(g.error, /unreadable/);
  });

  test('a graph with no nodes is refused', () => {
    const d = fresh();
    const out = path.join(d, 'graphify-out');
    fs.mkdirSync(out, { recursive: true });
    fs.writeFileSync(path.join(out, 'graph.json'), JSON.stringify({ nodes: [], links: [] }));
    assert.equal(G.load(path.join(out, 'graph.json')).ok, false);
  });

  test('edges naming absent nodes do not crash a traversal', () => {
    const gg = G.load(
      writeGraph(fresh(), { links: [{ source: 'ghost', target: 'base', relation: 'calls', confidence: 'EXTRACTED', weight: 1 }] })
    );
    const dep = G.dependents(gg, 'base');
    assert.equal(dep.length, 1);
    assert.equal(dep[0].node, undefined, 'a dangling id should resolve to no node, not throw');
  });
});
